spring:
  h2:
    console:
      enabled: true
      path: /h2

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 123456
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop